name: Update LeetCode Stats

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Count Problems
        run: |
          TOTAL=$(find . -name README.md | grep -v "./README.md" | wc -l)

          EASY=$(grep -R "Difficulty Easy" . --include="README.md" | wc -l)
          MEDIUM=$(grep -R "Difficulty Medium" . --include="README.md" | wc -l)
          HARD=$(grep -R "Difficulty Hard" . --include="README.md" | wc -l)

          sed -i "s/| Total Solved | Easy 🟢 | Medium 🟟 | Hard 🔴 |/| Total Solved | Easy 🟢 | Medium 🟡 | Hard 🔴 |/" README.md

          sed -i "/| Total Solved | Easy 🟢 | Medium 🟡 | Hard 🔴 |/{n;s/.*/| $TOTAL | $EASY | $MEDIUM | $HARD |/;}" README.md

          sed -i "/Easy   :/c\Easy   : $EASY" README.md
          sed -i "/Medium :/c\Medium : $MEDIUM" README.md
          sed -i "/Hard   :/c\Hard   : $HARD" README.md

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add README.md

          git diff --cached --quiet || git commit -m "Update repository stats"

          git push
